// =============================================================================
// ANCHOR CLIENT — IDL + Program Connection
// =============================================================================
// Provides a typed Anchor program handle for reading on-chain state from the
// memecoin protocol's Anchor programs (burn_controller, treasury_vault, etc.).
//
// USAGE:
//   import { getProgram } from "@/lib/anchor-client";
//   const program = getProgram(connection, wallet);
//   const treasury = await program.account.treasuryVault.fetch(TREASURY_PDA);
// =============================================================================

import { AnchorProvider, Program, type Idl } from "@coral-xyz/anchor";
import { Connection, type PublicKey } from "@solana/web3.js";
import type { AnchorWallet } from "@solana/wallet-adapter-react";
import { PROGRAM_ID, RPC_ENDPOINT } from "./constants";

// =============================================================================
// IDL PLACEHOLDER
// =============================================================================
// Replace with your generated IDL after `anchor build`:
//   import idl from "./idl/memecoin_protocol.json";
//
// The IDL is auto-generated by Anchor and contains all account types,
// instruction signatures, and event definitions.
// =============================================================================

const IDL_PLACEHOLDER: Idl = {
    version: "0.1.0",
    name: "memecoin_protocol",
    instructions: [],
    accounts: [],
    events: [],
    metadata: { address: PROGRAM_ID.toBase58() },
};

// =============================================================================
// READ-ONLY PROVIDER (no wallet required)
// =============================================================================

export function getReadOnlyProvider(): AnchorProvider {
    const connection = new Connection(RPC_ENDPOINT, "confirmed");

    // Dummy wallet for read-only — never signs transactions
    const readOnlyWallet = {
        publicKey: PROGRAM_ID, // placeholder
        signTransaction: async () => {
            throw new Error("Read-only provider cannot sign");
        },
        signAllTransactions: async () => {
            throw new Error("Read-only provider cannot sign");
        },
    } as AnchorWallet;

    return new AnchorProvider(connection, readOnlyWallet, {
        commitment: "confirmed",
    });
}

// =============================================================================
// WALLET-CONNECTED PROVIDER
// =============================================================================

export function getProvider(
    connection: Connection,
    wallet: AnchorWallet,
): AnchorProvider {
    return new AnchorProvider(connection, wallet, {
        commitment: "confirmed",
    });
}

// =============================================================================
// PROGRAM HANDLE
// =============================================================================

export function getProgram(
    connection: Connection,
    wallet?: AnchorWallet,
): Program {
    const provider = wallet
        ? getProvider(connection, wallet)
        : getReadOnlyProvider();

    // Replace IDL_PLACEHOLDER with actual IDL import after build
    return new Program(IDL_PLACEHOLDER, provider);
}

// =============================================================================
// ACCOUNT FETCH HELPERS
// =============================================================================

export async function fetchAccountData<T>(
    connection: Connection,
    accountPubkey: PublicKey,
    accountName: string,
    wallet?: AnchorWallet,
): Promise<T> {
    const program = getProgram(connection, wallet);
    const account = (program.account as Record<string, { fetch: (key: PublicKey) => Promise<T> }>)[accountName];
    if (!account) {
        throw new Error(`Unknown account type: ${accountName}`);
    }
    return account.fetch(accountPubkey);
}
